server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_APP_USER:ledger_app}
    password: ${POSTGRES_APP_PASSWORD:ledger_app_password}

ledger:
  node:
    nodeId: "node-2"
    leader: false
    peers:
      - "http://localhost:8081"
    allowedNodePublicKeys:
      node-1: "${LEDGER_NODE1_PUBLIC_KEY_BASE64:}"
