server:
  port: 8083

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER:ledger}
    password: ${POSTGRES_PASSWORD:ledger}

ledger:
  node:
    nodeId: "node-3"
    leader: false
    peers:
      - "http://localhost:8081"
    allowedNodePublicKeys:
      node-1: "${LEDGER_NODE1_PUBLIC_KEY_BASE64:}"
