package xavierroigmartin.v_integrity.infrastructure.config;

import jakarta.servlet.Filter;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.ServletRequest;
import jakarta.servlet.ServletResponse;
import java.io.IOException;
import org.slf4j.MDC;
import org.springframework.stereotype.Component;

/**
 * Filter to inject Node ID into the MDC (Mapped Diagnostic Context) for every request.
 * This ensures that logs generated by HTTP threads contain the "node_id" field.
 */
@Component
public class MdcFilter implements Filter {

  private final NodeProperties nodeProperties;

  MdcFilter(NodeProperties nodeProperties) {
    this.nodeProperties = nodeProperties;
  }

  @Override
  public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
      throws IOException, ServletException {
    try {
      MDC.put("node_id", nodeProperties.getNodeId());
      chain.doFilter(request, response);
    } finally {
      MDC.remove("node_id");
    }
  }
}
