package xavierroigmartin.v_integrity.infrastructure.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import org.springframework.boot.info.BuildProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Configuration for OpenAPI (Swagger) documentation.
 */
@Configuration
public class OpenApiConfig {

  private final BuildProperties buildProperties;

  /**
   * Constructor injection for build properties.
   *
   * @param buildProperties Properties generated by spring-boot-maven-plugin (build-info goal).
   */
  public OpenApiConfig(BuildProperties buildProperties) {
    this.buildProperties = buildProperties;
  }

  /**
   * Configures the OpenAPI bean with project-specific metadata.
   *
   * @return The configured OpenAPI instance.
   */
  @Bean
  public OpenAPI customOpenApi() {
    return new OpenAPI()
        .info(new Info()
            .title("V-Integrity Blockchain API")
            .version(buildProperties.getVersion())
            .description("Proof of Concept for a blockchain-based evidence integrity system.")
            .contact(new Contact()
                .name("Xavier Roig Martin")
                .url("https://github.com/xavierroigmartin"))
            .license(new License()
                .name("MIT License")
                .url("https://opensource.org/licenses/MIT")));
  }
}
